/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RenderedBlog } from "@ionic-internal/markdown-blog/src/models";
export namespace Components {
    interface AppBurger {
    }
    interface AppIcon {
        "name": string;
    }
    interface AppflowActivator {
    }
    interface AppflowSite {
    }
    interface AppflowSiteFooter {
    }
    interface AppflowSiteHeader {
    }
    interface AppflowSiteRoutes {
    }
    interface BlogNewsletter {
    }
    interface BlogPage {
        "slug"?: string;
        "viewMode": 'detail' | 'previews';
    }
    interface BlogPagination {
        "linkText": [string, string];
        "rssIcon": boolean;
    }
    interface BlogPost {
        "post"?: RenderedBlog;
        "preview": boolean;
        "slug"?: string;
    }
    interface BlogSearch {
    }
    interface BlogSocialActions {
        "column": boolean;
        "post"?: RenderedBlog;
    }
    interface BlogSubnav {
        "breadcrumbs": [string, string][];
        "pagination": boolean;
        "socialActions": boolean;
    }
    interface CodeSnippet {
        "code": string;
        "language": string;
    }
    interface GetStartedSection {
    }
    interface LandingPage {
    }
    interface MarkdownPage {
        "file": string;
    }
    interface NewsletterForm {
    }
    interface PhoneAnimator {
    }
    interface PipelineAnimator {
    }
    interface PlanPricing {
    }
    interface PricingPage {
    }
    interface PricingTable {
    }
    interface SiteBackdrop {
        "visible": boolean;
    }
    interface SiteImg {
        "alt": string;
        "dimensions": string;
        "loading"?: 'lazy' | 'eager';
        "name": string;
        "path": string;
        "type": string;
    }
    interface WhyAppflow {
    }
}
declare global {
    interface HTMLAppBurgerElement extends Components.AppBurger, HTMLStencilElement {
    }
    var HTMLAppBurgerElement: {
        prototype: HTMLAppBurgerElement;
        new (): HTMLAppBurgerElement;
    };
    interface HTMLAppIconElement extends Components.AppIcon, HTMLStencilElement {
    }
    var HTMLAppIconElement: {
        prototype: HTMLAppIconElement;
        new (): HTMLAppIconElement;
    };
    interface HTMLAppflowActivatorElement extends Components.AppflowActivator, HTMLStencilElement {
    }
    var HTMLAppflowActivatorElement: {
        prototype: HTMLAppflowActivatorElement;
        new (): HTMLAppflowActivatorElement;
    };
    interface HTMLAppflowSiteElement extends Components.AppflowSite, HTMLStencilElement {
    }
    var HTMLAppflowSiteElement: {
        prototype: HTMLAppflowSiteElement;
        new (): HTMLAppflowSiteElement;
    };
    interface HTMLAppflowSiteFooterElement extends Components.AppflowSiteFooter, HTMLStencilElement {
    }
    var HTMLAppflowSiteFooterElement: {
        prototype: HTMLAppflowSiteFooterElement;
        new (): HTMLAppflowSiteFooterElement;
    };
    interface HTMLAppflowSiteHeaderElement extends Components.AppflowSiteHeader, HTMLStencilElement {
    }
    var HTMLAppflowSiteHeaderElement: {
        prototype: HTMLAppflowSiteHeaderElement;
        new (): HTMLAppflowSiteHeaderElement;
    };
    interface HTMLAppflowSiteRoutesElement extends Components.AppflowSiteRoutes, HTMLStencilElement {
    }
    var HTMLAppflowSiteRoutesElement: {
        prototype: HTMLAppflowSiteRoutesElement;
        new (): HTMLAppflowSiteRoutesElement;
    };
    interface HTMLBlogNewsletterElement extends Components.BlogNewsletter, HTMLStencilElement {
    }
    var HTMLBlogNewsletterElement: {
        prototype: HTMLBlogNewsletterElement;
        new (): HTMLBlogNewsletterElement;
    };
    interface HTMLBlogPageElement extends Components.BlogPage, HTMLStencilElement {
    }
    var HTMLBlogPageElement: {
        prototype: HTMLBlogPageElement;
        new (): HTMLBlogPageElement;
    };
    interface HTMLBlogPaginationElement extends Components.BlogPagination, HTMLStencilElement {
    }
    var HTMLBlogPaginationElement: {
        prototype: HTMLBlogPaginationElement;
        new (): HTMLBlogPaginationElement;
    };
    interface HTMLBlogPostElement extends Components.BlogPost, HTMLStencilElement {
    }
    var HTMLBlogPostElement: {
        prototype: HTMLBlogPostElement;
        new (): HTMLBlogPostElement;
    };
    interface HTMLBlogSearchElement extends Components.BlogSearch, HTMLStencilElement {
    }
    var HTMLBlogSearchElement: {
        prototype: HTMLBlogSearchElement;
        new (): HTMLBlogSearchElement;
    };
    interface HTMLBlogSocialActionsElement extends Components.BlogSocialActions, HTMLStencilElement {
    }
    var HTMLBlogSocialActionsElement: {
        prototype: HTMLBlogSocialActionsElement;
        new (): HTMLBlogSocialActionsElement;
    };
    interface HTMLBlogSubnavElement extends Components.BlogSubnav, HTMLStencilElement {
    }
    var HTMLBlogSubnavElement: {
        prototype: HTMLBlogSubnavElement;
        new (): HTMLBlogSubnavElement;
    };
    interface HTMLCodeSnippetElement extends Components.CodeSnippet, HTMLStencilElement {
    }
    var HTMLCodeSnippetElement: {
        prototype: HTMLCodeSnippetElement;
        new (): HTMLCodeSnippetElement;
    };
    interface HTMLGetStartedSectionElement extends Components.GetStartedSection, HTMLStencilElement {
    }
    var HTMLGetStartedSectionElement: {
        prototype: HTMLGetStartedSectionElement;
        new (): HTMLGetStartedSectionElement;
    };
    interface HTMLLandingPageElement extends Components.LandingPage, HTMLStencilElement {
    }
    var HTMLLandingPageElement: {
        prototype: HTMLLandingPageElement;
        new (): HTMLLandingPageElement;
    };
    interface HTMLMarkdownPageElement extends Components.MarkdownPage, HTMLStencilElement {
    }
    var HTMLMarkdownPageElement: {
        prototype: HTMLMarkdownPageElement;
        new (): HTMLMarkdownPageElement;
    };
    interface HTMLNewsletterFormElement extends Components.NewsletterForm, HTMLStencilElement {
    }
    var HTMLNewsletterFormElement: {
        prototype: HTMLNewsletterFormElement;
        new (): HTMLNewsletterFormElement;
    };
    interface HTMLPhoneAnimatorElement extends Components.PhoneAnimator, HTMLStencilElement {
    }
    var HTMLPhoneAnimatorElement: {
        prototype: HTMLPhoneAnimatorElement;
        new (): HTMLPhoneAnimatorElement;
    };
    interface HTMLPipelineAnimatorElement extends Components.PipelineAnimator, HTMLStencilElement {
    }
    var HTMLPipelineAnimatorElement: {
        prototype: HTMLPipelineAnimatorElement;
        new (): HTMLPipelineAnimatorElement;
    };
    interface HTMLPlanPricingElement extends Components.PlanPricing, HTMLStencilElement {
    }
    var HTMLPlanPricingElement: {
        prototype: HTMLPlanPricingElement;
        new (): HTMLPlanPricingElement;
    };
    interface HTMLPricingPageElement extends Components.PricingPage, HTMLStencilElement {
    }
    var HTMLPricingPageElement: {
        prototype: HTMLPricingPageElement;
        new (): HTMLPricingPageElement;
    };
    interface HTMLPricingTableElement extends Components.PricingTable, HTMLStencilElement {
    }
    var HTMLPricingTableElement: {
        prototype: HTMLPricingTableElement;
        new (): HTMLPricingTableElement;
    };
    interface HTMLSiteBackdropElement extends Components.SiteBackdrop, HTMLStencilElement {
    }
    var HTMLSiteBackdropElement: {
        prototype: HTMLSiteBackdropElement;
        new (): HTMLSiteBackdropElement;
    };
    interface HTMLSiteImgElement extends Components.SiteImg, HTMLStencilElement {
    }
    var HTMLSiteImgElement: {
        prototype: HTMLSiteImgElement;
        new (): HTMLSiteImgElement;
    };
    interface HTMLWhyAppflowElement extends Components.WhyAppflow, HTMLStencilElement {
    }
    var HTMLWhyAppflowElement: {
        prototype: HTMLWhyAppflowElement;
        new (): HTMLWhyAppflowElement;
    };
    interface HTMLElementTagNameMap {
        "app-burger": HTMLAppBurgerElement;
        "app-icon": HTMLAppIconElement;
        "appflow-activator": HTMLAppflowActivatorElement;
        "appflow-site": HTMLAppflowSiteElement;
        "appflow-site-footer": HTMLAppflowSiteFooterElement;
        "appflow-site-header": HTMLAppflowSiteHeaderElement;
        "appflow-site-routes": HTMLAppflowSiteRoutesElement;
        "blog-newsletter": HTMLBlogNewsletterElement;
        "blog-page": HTMLBlogPageElement;
        "blog-pagination": HTMLBlogPaginationElement;
        "blog-post": HTMLBlogPostElement;
        "blog-search": HTMLBlogSearchElement;
        "blog-social-actions": HTMLBlogSocialActionsElement;
        "blog-subnav": HTMLBlogSubnavElement;
        "code-snippet": HTMLCodeSnippetElement;
        "get-started-section": HTMLGetStartedSectionElement;
        "landing-page": HTMLLandingPageElement;
        "markdown-page": HTMLMarkdownPageElement;
        "newsletter-form": HTMLNewsletterFormElement;
        "phone-animator": HTMLPhoneAnimatorElement;
        "pipeline-animator": HTMLPipelineAnimatorElement;
        "plan-pricing": HTMLPlanPricingElement;
        "pricing-page": HTMLPricingPageElement;
        "pricing-table": HTMLPricingTableElement;
        "site-backdrop": HTMLSiteBackdropElement;
        "site-img": HTMLSiteImgElement;
        "why-appflow": HTMLWhyAppflowElement;
    }
}
declare namespace LocalJSX {
    interface AppBurger {
        "onBurgerClick"?: (event: CustomEvent<any>) => void;
    }
    interface AppIcon {
        "name": string;
    }
    interface AppflowActivator {
    }
    interface AppflowSite {
    }
    interface AppflowSiteFooter {
    }
    interface AppflowSiteHeader {
    }
    interface AppflowSiteRoutes {
    }
    interface BlogNewsletter {
    }
    interface BlogPage {
        "slug"?: string;
        "viewMode"?: 'detail' | 'previews';
    }
    interface BlogPagination {
        "linkText"?: [string, string];
        "rssIcon"?: boolean;
    }
    interface BlogPost {
        "post"?: RenderedBlog;
        "preview"?: boolean;
        "slug"?: string;
    }
    interface BlogSearch {
    }
    interface BlogSocialActions {
        "column"?: boolean;
        "post"?: RenderedBlog;
    }
    interface BlogSubnav {
        "breadcrumbs"?: [string, string][];
        "pagination"?: boolean;
        "socialActions"?: boolean;
    }
    interface CodeSnippet {
        "code": string;
        "language": string;
    }
    interface GetStartedSection {
    }
    interface LandingPage {
    }
    interface MarkdownPage {
        "file": string;
    }
    interface NewsletterForm {
    }
    interface PhoneAnimator {
    }
    interface PipelineAnimator {
    }
    interface PlanPricing {
    }
    interface PricingPage {
    }
    interface PricingTable {
    }
    interface SiteBackdrop {
        "visible"?: boolean;
    }
    interface SiteImg {
        "alt": string;
        "dimensions": string;
        "loading"?: 'lazy' | 'eager';
        "name": string;
        "path": string;
        "type": string;
    }
    interface WhyAppflow {
    }
    interface IntrinsicElements {
        "app-burger": AppBurger;
        "app-icon": AppIcon;
        "appflow-activator": AppflowActivator;
        "appflow-site": AppflowSite;
        "appflow-site-footer": AppflowSiteFooter;
        "appflow-site-header": AppflowSiteHeader;
        "appflow-site-routes": AppflowSiteRoutes;
        "blog-newsletter": BlogNewsletter;
        "blog-page": BlogPage;
        "blog-pagination": BlogPagination;
        "blog-post": BlogPost;
        "blog-search": BlogSearch;
        "blog-social-actions": BlogSocialActions;
        "blog-subnav": BlogSubnav;
        "code-snippet": CodeSnippet;
        "get-started-section": GetStartedSection;
        "landing-page": LandingPage;
        "markdown-page": MarkdownPage;
        "newsletter-form": NewsletterForm;
        "phone-animator": PhoneAnimator;
        "pipeline-animator": PipelineAnimator;
        "plan-pricing": PlanPricing;
        "pricing-page": PricingPage;
        "pricing-table": PricingTable;
        "site-backdrop": SiteBackdrop;
        "site-img": SiteImg;
        "why-appflow": WhyAppflow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-burger": LocalJSX.AppBurger & JSXBase.HTMLAttributes<HTMLAppBurgerElement>;
            "app-icon": LocalJSX.AppIcon & JSXBase.HTMLAttributes<HTMLAppIconElement>;
            "appflow-activator": LocalJSX.AppflowActivator & JSXBase.HTMLAttributes<HTMLAppflowActivatorElement>;
            "appflow-site": LocalJSX.AppflowSite & JSXBase.HTMLAttributes<HTMLAppflowSiteElement>;
            "appflow-site-footer": LocalJSX.AppflowSiteFooter & JSXBase.HTMLAttributes<HTMLAppflowSiteFooterElement>;
            "appflow-site-header": LocalJSX.AppflowSiteHeader & JSXBase.HTMLAttributes<HTMLAppflowSiteHeaderElement>;
            "appflow-site-routes": LocalJSX.AppflowSiteRoutes & JSXBase.HTMLAttributes<HTMLAppflowSiteRoutesElement>;
            "blog-newsletter": LocalJSX.BlogNewsletter & JSXBase.HTMLAttributes<HTMLBlogNewsletterElement>;
            "blog-page": LocalJSX.BlogPage & JSXBase.HTMLAttributes<HTMLBlogPageElement>;
            "blog-pagination": LocalJSX.BlogPagination & JSXBase.HTMLAttributes<HTMLBlogPaginationElement>;
            "blog-post": LocalJSX.BlogPost & JSXBase.HTMLAttributes<HTMLBlogPostElement>;
            "blog-search": LocalJSX.BlogSearch & JSXBase.HTMLAttributes<HTMLBlogSearchElement>;
            "blog-social-actions": LocalJSX.BlogSocialActions & JSXBase.HTMLAttributes<HTMLBlogSocialActionsElement>;
            "blog-subnav": LocalJSX.BlogSubnav & JSXBase.HTMLAttributes<HTMLBlogSubnavElement>;
            "code-snippet": LocalJSX.CodeSnippet & JSXBase.HTMLAttributes<HTMLCodeSnippetElement>;
            "get-started-section": LocalJSX.GetStartedSection & JSXBase.HTMLAttributes<HTMLGetStartedSectionElement>;
            "landing-page": LocalJSX.LandingPage & JSXBase.HTMLAttributes<HTMLLandingPageElement>;
            "markdown-page": LocalJSX.MarkdownPage & JSXBase.HTMLAttributes<HTMLMarkdownPageElement>;
            "newsletter-form": LocalJSX.NewsletterForm & JSXBase.HTMLAttributes<HTMLNewsletterFormElement>;
            "phone-animator": LocalJSX.PhoneAnimator & JSXBase.HTMLAttributes<HTMLPhoneAnimatorElement>;
            "pipeline-animator": LocalJSX.PipelineAnimator & JSXBase.HTMLAttributes<HTMLPipelineAnimatorElement>;
            "plan-pricing": LocalJSX.PlanPricing & JSXBase.HTMLAttributes<HTMLPlanPricingElement>;
            "pricing-page": LocalJSX.PricingPage & JSXBase.HTMLAttributes<HTMLPricingPageElement>;
            "pricing-table": LocalJSX.PricingTable & JSXBase.HTMLAttributes<HTMLPricingTableElement>;
            "site-backdrop": LocalJSX.SiteBackdrop & JSXBase.HTMLAttributes<HTMLSiteBackdropElement>;
            "site-img": LocalJSX.SiteImg & JSXBase.HTMLAttributes<HTMLSiteImgElement>;
            "why-appflow": LocalJSX.WhyAppflow & JSXBase.HTMLAttributes<HTMLWhyAppflowElement>;
        }
    }
}
